// Mocks generated by Mockito 5.4.2 from annotations
// in nba_hub/test/unit_test/game_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nba_hub/core/failure/failure.dart' as _i6;
import 'package:nba_hub/features/games/domain/entity/game_entity.dart' as _i7;
import 'package:nba_hub/features/games/domain/repository/game_repository.dart'
    as _i2;
import 'package:nba_hub/features/games/domain/use_case/game_use_case.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIGameRepository_0 extends _i1.SmartFake
    implements _i2.IGameRepository {
  _FakeIGameRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameUseCase extends _i1.Mock implements _i4.GameUseCase {
  @override
  _i2.IGameRepository get gameRepository => (super.noSuchMethod(
        Invocation.getter(#gameRepository),
        returnValue: _FakeIGameRepository_0(
          this,
          Invocation.getter(#gameRepository),
        ),
        returnValueForMissingStub: _FakeIGameRepository_0(
          this,
          Invocation.getter(#gameRepository),
        ),
      ) as _i2.IGameRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.GameEntity>>> getAllGames() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllGames,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.GameEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.GameEntity>>(
          this,
          Invocation.method(
            #getAllGames,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.GameEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.GameEntity>>(
          this,
          Invocation.method(
            #getAllGames,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.GameEntity>>>);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.GameEntity>>> getAllGameByDate(
    String? season,
    String? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllGameByDate,
          [
            season,
            date,
          ],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.GameEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.GameEntity>>(
          this,
          Invocation.method(
            #getAllGameByDate,
            [
              season,
              date,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.GameEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.GameEntity>>(
          this,
          Invocation.method(
            #getAllGameByDate,
            [
              season,
              date,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.GameEntity>>>);
}
